/**
 * @category   Technobit
 * @package    Technobit_Banner
 * @author     Technobit Team
 * @copyright  This file was generated by using Module Creator provided by <kaushalpatel531.kp@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

define([
    'jquery',
    'owlCarousel'
], function ($) {
    'use strict';

    $.widget('technobit.banner', {
        options: {
            loop:true,
            autoplay:true,
            autoplayTimeout:5000,
            autoplayHoverPause:true,
            items:1,
            margin:0,
            stagePadding:0,
            smartSpeed:450,
            slideSpeed: 500,
            nav:true,
            navText:[],
            navElement:'div',
            dots: false
        },
        _create: function() {
             $(this.element).owlCarousel(this.options);
        }
    });

    return $.technobit.banner;
});
